-- 040_expand_interests_catalog.sql
-- Fügt den vollständigen Interessenkatalog ein (~95 Einträge).
-- Die ursprünglichen 30 Interessen wurden über den Demo-Seed angelegt.
-- Der Seed ist idempotent (skippt bestehende User) und hat die neuen Einträge
-- nie in die interests-Tabelle geschrieben. Diese Migration holt das nach.
-- Alle INSERTs verwenden ON CONFLICT DO NOTHING — sicher mehrfach ausführbar.

INSERT INTO interests (id, name_de) VALUES
  (uuid_generate_v4(), '3D-Druck'),
  (uuid_generate_v4(), 'Anime'),
  (uuid_generate_v4(), 'Astrologie'),
  (uuid_generate_v4(), 'Astronomie'),
  (uuid_generate_v4(), 'Basketball'),
  (uuid_generate_v4(), 'BBQ'),
  (uuid_generate_v4(), 'Bogenschießen'),
  (uuid_generate_v4(), 'Brettspiele'),
  (uuid_generate_v4(), 'Brotbacken'),
  (uuid_generate_v4(), 'Camping'),
  (uuid_generate_v4(), 'Comics'),
  (uuid_generate_v4(), 'Craft Beer'),
  (uuid_generate_v4(), 'Cybersecurity'),
  (uuid_generate_v4(), 'Escape Rooms'),
  (uuid_generate_v4(), 'Fußball'),
  (uuid_generate_v4(), 'Geschichte'),
  (uuid_generate_v4(), 'Hardware'),
  (uuid_generate_v4(), 'Hip-Hop'),
  (uuid_generate_v4(), 'Jazz'),
  (uuid_generate_v4(), 'Journaling'),
  (uuid_generate_v4(), 'Kalligraphie'),
  (uuid_generate_v4(), 'Kältebad'),
  (uuid_generate_v4(), 'Kampfsport'),
  (uuid_generate_v4(), 'Kanufahren'),
  (uuid_generate_v4(), 'Karaoke'),
  (uuid_generate_v4(), 'Keramik'),
  (uuid_generate_v4(), 'KI & Machine Learning'),
  (uuid_generate_v4(), 'Klettersteig'),
  (uuid_generate_v4(), 'K-Pop'),
  (uuid_generate_v4(), 'Manga'),
  (uuid_generate_v4(), 'Metal'),
  (uuid_generate_v4(), 'Minimalismus'),
  (uuid_generate_v4(), 'MTB'),
  (uuid_generate_v4(), 'Museen'),
  (uuid_generate_v4(), 'Nachhaltigkeit'),
  (uuid_generate_v4(), 'Open Source'),
  (uuid_generate_v4(), 'Philosophie'),
  (uuid_generate_v4(), 'Sauna'),
  (uuid_generate_v4(), 'Schauspiel'),
  (uuid_generate_v4(), 'Schreiben'),
  (uuid_generate_v4(), 'Schwimmen'),
  (uuid_generate_v4(), 'Siebdruck'),
  (uuid_generate_v4(), 'Smart Home'),
  (uuid_generate_v4(), 'Startups'),
  (uuid_generate_v4(), 'Streetfood'),
  (uuid_generate_v4(), 'Surfen'),
  (uuid_generate_v4(), 'Sushi'),
  (uuid_generate_v4(), 'Tauchen'),
  (uuid_generate_v4(), 'Techno'),
  (uuid_generate_v4(), 'Tee'),
  (uuid_generate_v4(), 'Tennis'),
  (uuid_generate_v4(), 'Theater'),
  (uuid_generate_v4(), 'Veganes Kochen'),
  (uuid_generate_v4(), 'Vinyl'),
  (uuid_generate_v4(), 'Wein'),
  (uuid_generate_v4(), 'Zeichnen'),
  -- Red-Flag-Interessen (is_green implizit NULL — Anzeige im Profil-Editor wählbar)
  (uuid_generate_v4(), 'Arroganz'),
  (uuid_generate_v4(), 'Ausreden'),
  (uuid_generate_v4(), 'Bürokratie'),
  (uuid_generate_v4(), 'Drama'),
  (uuid_generate_v4(), 'Eifersucht'),
  (uuid_generate_v4(), 'Engstirnigkeit'),
  (uuid_generate_v4(), 'Fake News'),
  (uuid_generate_v4(), 'Faulheit'),
  (uuid_generate_v4(), 'Handysucht'),
  (uuid_generate_v4(), 'Ignoranz'),
  (uuid_generate_v4(), 'Klatsch & Tratsch'),
  (uuid_generate_v4(), 'Kontrollverlust'),
  (uuid_generate_v4(), 'Lärm'),
  (uuid_generate_v4(), 'Micromanagement'),
  (uuid_generate_v4(), 'Negativität'),
  (uuid_generate_v4(), 'Oberflächlichkeit'),
  (uuid_generate_v4(), 'Passiv-Aggression'),
  (uuid_generate_v4(), 'Pedanterie'),
  (uuid_generate_v4(), 'Spoiler'),
  (uuid_generate_v4(), 'Überheblichkeit'),
  (uuid_generate_v4(), 'Ungeduld'),
  (uuid_generate_v4(), 'Unordnung'),
  (uuid_generate_v4(), 'Unzuverlässigkeit'),
  (uuid_generate_v4(), 'Zu spät kommen')
ON CONFLICT (name_de) DO NOTHING;
